import "./globals.css";
import { Poppins } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Sidebar />
        <div className="sm:ml-64">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
